services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - sqlserver
    networks:
      - laravel

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "*Usuario00!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge