version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TuPasswordFuerte123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge